'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Shoeglue.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bomb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bomb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0000000000000000
        '''0000000000000000
        '''0000000000000000
        '''0000000000000000
        '''0000000000000000
        '''0000000000000000
        '''0000000000000000
        '''0000000000000000
        '''0000000000000000
        '''0000000000000000
        '''6000000000000007
        '''1111111111111111
        '''120
        '''160
        '''Use the arrow keys to move. You need a key to open a door..
        '''</summary>
        Friend ReadOnly Property level0() As String
            Get
                Return ResourceManager.GetString("level0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0000000000000000
        '''0000000000000000
        '''0000000000000000
        '''0006000000000000
        '''0003000000000000
        '''0003000000000000
        '''0003333111000000
        '''0000003000000000
        '''0000003000000000
        '''0000003000000000
        '''0000003001307000
        '''1111111111111111
        '''24
        '''160
        '''You can&apos;t jump. Use ladders instead. Use the arrow keys to climb ladders..
        '''</summary>
        Friend ReadOnly Property level1() As String
            Get
                Return ResourceManager.GetString("level1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0000000000000000
        '''0000007000000000
        '''0000311100000000
        '''0000311100000000
        '''0000300100000000
        '''0000316100000000
        '''0000314100000000
        '''0000312100000000
        '''0000300000000000
        '''2220300000000000
        '''2420300000000000
        '''1111111111111111
        '''16
        '''160
        '''Press Space to drop a bomb. Use bombs to blow up walls..
        '''</summary>
        Friend ReadOnly Property level2() As String
            Get
                Return ResourceManager.GetString("level2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1111111111111111
        '''1555555555555551
        '''1111111111111151
        '''1555555555555551
        '''1511111111111111
        '''1555555555555551
        '''1111111111111151
        '''1555555555555551
        '''1511111111111111
        '''1555555555555671
        '''1111111111111111
        '''1111111111111111
        '''16
        '''16
        '''Collect coins. You need these to unlock areas..
        '''</summary>
        Friend ReadOnly Property level3() As String
            Get
                Return ResourceManager.GetString("level3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0000000000000000
        '''0062700004000000
        '''0312211111300000
        '''0338833333300000
        '''0008800000000000
        '''0000000000000000
        '''0000000000000000
        '''0000000000000000
        '''0000000000000000
        '''0000000000000000
        '''0000000000000000
        '''1111111111111111
        '''120
        '''16
        '''If you mess up, try again! Press F9 to restart the level.
        '''.
        '''</summary>
        Friend ReadOnly Property level4() As String
            Get
                Return ResourceManager.GetString("level4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0000000000000000
        '''0000000000000000
        '''0000000000000000
        '''0000000000000000
        '''0038888800000000
        '''0030000038880000
        '''0030000030400000
        '''8888881028800000
        '''0000012021001000
        '''6000012221888000
        '''8888308880000000
        '''0007888888888800
        '''96
        '''96
        '''You are on your own now. Level 6-1: Invisible Maze.
        '''</summary>
        Friend ReadOnly Property level5() As String
            Get
                Return ResourceManager.GetString("level5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0000111133333311
        '''0000130000041361
        '''0111131881221331
        '''0122031701001331
        '''0133111351001331
        '''0133100351001331
        '''0133100351001331
        '''0133100351001331
        '''0133100351001331
        '''0133100351001331
        '''0133400351000331
        '''0111111111088888
        '''121
        '''32
        '''Level 7-1: Ladder something.
        '''</summary>
        Friend ReadOnly Property level6() As String
            Get
                Return ResourceManager.GetString("level6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0000000000000000
        '''0000000000000000
        '''0000000000000000
        '''0000000000000000
        '''0000000000000000
        '''0000000000000000
        '''0000000000000000
        '''0000000006000000
        '''0000333333333333
        '''0000402205550003
        '''0000007100000003
        '''0000001111888888
        '''128
        '''160
        '''Level 8-1: End of port version 1.0.0 This is the end of the PC port Version 1.0.0.
        '''</summary>
        Friend ReadOnly Property level7() As String
            Get
                Return ResourceManager.GetString("level7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
